"""
GOTHAM Data Loader
Reads JSON files generated by generate_data.py and loads them into PostgreSQL.
"""
import json
import os
from datetime import datetime
from database import SessionLocal, Base, engine, Unit, CaseMaster, Accused, CaseAccused, \
    Victim, ArrestSurrender, VehicleRecord, PhysicalDescriptor

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")


def parse_dt(s):
    """Parse ISO datetime string, return None on failure."""
    if not s:
        return None
    try:
        return datetime.fromisoformat(s)
    except Exception:
        return None


def load_all():
    """Load all generated JSON data into the database."""
    print("🔧 GOTHAM Data Loader — Loading synthetic data into PostgreSQL...")
    print("─" * 60)

    # Create tables
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    try:
        # ── Units ──
        with open(os.path.join(DATA_DIR, "units.json")) as f:
            units = json.load(f)
        for u in units:
            db.merge(Unit(unit_id=u["unit_id"], unit_name=u["unit_name"],
                          district=u["district"], lat=u["lat"], lng=u["lng"]))
        db.commit()
        print(f"✅ Loaded {len(units)} police units")

        # ── Accused ──
        with open(os.path.join(DATA_DIR, "accused.json")) as f:
            accused_list = json.load(f)
        for a in accused_list:
            db.merge(Accused(
                accused_id=a["accused_id"], name=a["name"],
                dob=datetime.strptime(a["dob"], "%Y-%m-%d").date() if a.get("dob") else None,
                gender=a["gender"], address=a["address"], district=a["district"],
                risk_score=a["risk_score"], risk_label=a["risk_label"],
                prior_offense_count=a["prior_offense_count"], mo_pattern=a["mo_pattern"]
            ))
        db.commit()
        print(f"✅ Loaded {len(accused_list)} accused")

        # ── FIRs ──
        with open(os.path.join(DATA_DIR, "firs.json")) as f:
            firs = json.load(f)
        for fir in firs:
            db.merge(CaseMaster(
                fir_id=fir["fir_id"], fir_number=fir["fir_number"],
                unit_id=fir["unit_id"], crime_type=fir["crime_type"],
                crime_subtype=fir.get("crime_subtype", "General"),
                date_of_occurrence=parse_dt(fir["date_of_occurrence"]),
                date_reported=parse_dt(fir["date_reported"]),
                lat=fir["lat"], lng=fir["lng"],
                brief_facts=fir["brief_facts"], status=fir["status"],
                severity_weight=fir["severity_weight"],
                mo_tags=fir.get("mo_tags", []),
                summary=fir.get("summary", "")
            ))
        db.commit()
        print(f"✅ Loaded {len(firs)} FIRs")

        # ── Case-Accused Links ──
        with open(os.path.join(DATA_DIR, "case_accused.json")) as f:
            links = json.load(f)
        for link in links:
            try:
                db.merge(CaseAccused(
                    fir_id=link["fir_id"], accused_id=link["accused_id"], role=link["role"]
                ))
            except Exception:
                db.rollback()
                continue
        db.commit()
        print(f"✅ Loaded {len(links)} case-accused links")

        # ── Victims ──
        with open(os.path.join(DATA_DIR, "victims.json")) as f:
            victims = json.load(f)
        for v in victims:
            db.merge(Victim(
                victim_id=v["victim_id"], fir_id=v["fir_id"], name=v["name"],
                age=v["age"], gender=v["gender"], address=v["address"],
                occupation=v["occupation"]
            ))
        db.commit()
        print(f"✅ Loaded {len(victims)} victims")

        # ── Arrests ──
        arrests_path = os.path.join(DATA_DIR, "arrests.json")
        if os.path.exists(arrests_path):
            with open(arrests_path) as f:
                arrests = json.load(f)
            for a in arrests:
                db.merge(ArrestSurrender(
                    arrest_id=a["arrest_id"], accused_id=a["accused_id"],
                    fir_id=a["fir_id"], arrest_date=parse_dt(a["arrest_date"]),
                    arrest_type=a["arrest_type"]
                ))
            db.commit()
            print(f"✅ Loaded {len(arrests)} arrest records")

        # ── Physical Descriptors ──
        desc_path = os.path.join(DATA_DIR, "physical_descriptors.json")
        if os.path.exists(desc_path):
            with open(desc_path) as f:
                descriptors = json.load(f)
            for d in descriptors:
                db.merge(PhysicalDescriptor(
                    descriptor_id=d["descriptor_id"], accused_id=d["accused_id"],
                    height_cm=d["height_cm"], build=d["build"],
                    distinguishing_marks=d["distinguishing_marks"],
                    approximate_age_at_filing=d["approximate_age_at_filing"],
                    source_fir_id=d.get("source_fir_id")
                ))
            db.commit()
            print(f"✅ Loaded {len(descriptors)} physical descriptors")

        # ── Vehicle Records ──
        veh_path = os.path.join(DATA_DIR, "vehicle_records.json")
        if os.path.exists(veh_path):
            with open(veh_path) as f:
                vehicles = json.load(f)
            for v in vehicles:
                db.merge(VehicleRecord(
                    vehicle_id=v["vehicle_id"],
                    registration_partial=v["registration_partial"],
                    vehicle_type=v["vehicle_type"], color=v["color"],
                    make=v["make"], fir_id=v.get("fir_id"),
                    confidence=v["confidence"]
                ))
            db.commit()
            print(f"✅ Loaded {len(vehicles)} vehicle records")

        print("─" * 60)
        print("🚀 All data loaded successfully into PostgreSQL!")

    except Exception as e:
        db.rollback()
        print(f"❌ Error loading data: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    load_all()
